[package]
name = "basic-shimmer"
version = "0.1.0"
edition = "2021"

[lib]
name = "basic"
crate_type = ["dylib"]

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.141"
redhook = "2.0.0"
shimmer = { path = "../.." }
